# Generated by Django 5.2.8 on 2025-11-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PinNum',
            new_name='Pin_Num',
        ),
        migrations.AddField(
            model_name='profile',
            name='Acc_Num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Customer',
            field=models.CharField(max_length=100),
        ),
    ]
