# Generated by Django 5.2.8 on 2025-11-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0002_rename_pinnum_pin_num_profile_acc_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Customer',
            field=models.CharField(max_length=200),
        ),
    ]
