# Generated by Django 5.2.8 on 2025-11-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0003_alter_profile_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Ifsc',
            field=models.IntegerField(default=0),
        ),
    ]
