# Generated by Django 5.2.8 on 2025-11-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0004_alter_profile_ifsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Ifsc',
            field=models.CharField(max_length=200),
        ),
    ]
