# Generated by Django 5.2.8 on 2025-11-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0005_alter_profile_ifsc'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(max_length=100)),
                ('account_number', models.IntegerField(default=0)),
            ],
        ),
    ]
