# Generated by Django 5.2.8 on 2025-11-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0006_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Acc_Num',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Customer',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='Ifsc',
            field=models.CharField(max_length=20),
        ),
    ]
