# Generated by Django 5.2.8 on 2025-11-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0007_remove_profile_acc_num_remove_profile_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin_num',
            name='account_number',
            field=models.IntegerField(default=0),
        ),
    ]
