# Generated by Django 5.2.8 on 2025-11-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0008_pin_num_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin_num',
            name='account_number',
        ),
    ]
